<?php

use Hoda\OneCountry;
use Hoda\Repositories\CountryRepository;
use Hoda\Router;
use Hoda\Services\CountryService;
use Hoda\TwoCountries;
use PHPUnit\Framework\TestCase;

class RouterTest extends TestCase
{
    private $router;

    public function setUp()
    {
//        $router = IoC::resolve('router');

        $router = new Router(new OneCountry(new CountryService(new CountryRepository())),
            new TwoCountries(new CountryService(new CountryRepository())));

//        $router = new Router();
        $this->router = $router;
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testNoInputs()
    {

        $this->expectException(InvalidArgumentException::class);
        $this->router->route(['index.php']);
    }
    public function testCountryIsNotValid()
    {
        $this->expectException(InvalidArgumentException::class);
        $this->router->route(['index.php','misr']);
    }
}
